Editing text when using the DialogManager.reset_stack() method
Tishka17/aiogram_dialog pull request #213
Opened 2022-11-19 21:07 UTC by Shaonis

The DialogManager method reset_stack now has a new positional argument «new_text».

It accepts a string or None:
• If new_text="some string", the message text is edited to the specified
• If new_text=None, then the message is not edited

I've tried to add a «Shao-mod» comment to each modified piece of code.

2022-11-19 21:32 UTC, bomzheg requested changes
please remove redundant comments, move new arg to end. My other coments are questions/minor/IMHO

2022-11-19 21:32 UTC, bomzheg commented on aiogram_dialog/api/protocols/manager.py
> +    async def reset_stack(self, new_text: Optional[str], remove_keyboard: bool = True) -> None:
i think new argument should be last in positional args and should have default value (`None`?)

2022-11-19 21:32 UTC, bomzheg commented on aiogram_dialog/api/protocols/manager.py
> +    # Shao-mod
please remove redundant comments

2022-11-19 21:32 UTC, bomzheg commented on aiogram_dialog/api/protocols/message_manager.py
> +    # Shao-mod
please delete all related comments

2022-11-19 21:32 UTC, bomzheg commented on aiogram_dialog/manager/manager.py
> +    async def reset_stack(self, new_text: Optional[str], remove_keyboard: bool = True) -> None:
also move new arg to the end of args

2022-11-19 21:32 UTC, bomzheg commented on aiogram_dialog/manager/message_manager.py
> +            if old_message.photo:
And if `old_message.audio` is present? Probably check `if message.caption` here?

But media can be without captions. What if check here content-type of message?

2022-11-19 21:32 UTC, bomzheg commented on aiogram_dialog/manager/message_manager.py
> +            if old_message.photo:
and if `old_message.audio` is present? probably check `if message.caption` here?

2022-11-19 21:32 UTC, bomzheg commented on aiogram_dialog/api/protocols/message_manager.py
> +    async def new_text(self, bot: Bot, new_text: str, old_message: Optional[Message]):
I dont like this name. 

`replace_text`? `update_text`?

2022-11-19 21:32 UTC, bomzheg commented on aiogram_dialog/manager/manager.py
> +        # self.current_stack().last_message_id = None - might need to be corrected
i don't understad, what do you want to correct here

2022-11-20 16:50 UTC, Shaonis reviewed
I took the advice into account. Changes:
- The new_text attribute is renamed to update_text
- update_text comes after the remove_keyboard attribute
- by default update_text=None
- comments removed
- all types of messages should be supported (the function tree of message editing from the original code was used)

2022-11-20 17:01 UTC, bomzheg commented on aiogram_dialog/manager/manager.py
> +            await self.reset_stack(remove_keyboard=False, update_text=None)
i think it's redundant to add default arg to this invocation. it's already declared on method definition

2022-11-20 17:01 UTC, bomzheg commented on aiogram_dialog/manager/message_manager.py
> +            disable_web_page_preview=True,
last two parameters are too specific for library. What if user want to show web page preview?

2022-11-20 17:01 UTC, bomzheg commented on aiogram_dialog/manager/message_manager.py
> +            media=old_message.media_group_id,
are you sure? i think media is something like photo|video|aniomation|..

2022-11-20 17:01 UTC, bomzheg commented on aiogram_dialog/manager/manager.py
> +            await self._update_text(new_text=update_text, reset_last_message_id=True)
i dont understand. Why in case of `update_text` we need to reset stack and do not need in case of `remove_keyboard and update_text`

2022-11-21 06:07 UTC, Shaonis commented
The new update_text argument was created to conveniently and visually edit the text when using the DialogManager.reset_stack() method.

There are alternative ways to edit, but in such cases you need to either refer to the event or figure out how to switch to another state, generally write more code.

I decided to propose this innovation because I wanted to conveniently solve my situation:

class ApplicationData(StatesGroup):
         name = State()
         age = State()
         phone_number = State()
         connection = state()
         description = state()

My FSM machine remembers 5 (State) entered data from user. But in the last ApplicationData.description I need to get some prepared responses from the user. For this I use 1 dialog with Multiselect. I write when selecting: "How can I describe your situation?". After the user presses the ready button, the keyboard disappears and the text remains, which I don't like. Then I started looking for ways to elegantly edit the message to "Thank you, your request is accepted". And eventually I wanted to try to make a new argument for the method when resetting the dialog (reset_stack) for new text for nice and convenient editing, so as not to write "unnecessary" in my opinion.

2022-11-21 11:02 UTC, closed without merging